Moved pluginval test to msbuild CI job

diff --git a/.github/workflows/win-build-validate.yml b/.github/workflows/win-build-validate.yml
--- a/.github/workflows/win-build-validate.yml
+++ b/.github/workflows/win-build-validate.yml
@@ -1,4 +1,4 @@
-name: MSBuild
+name: Windows Build & Validate
 
 on:
   push:
@@ -37,3 +37,11 @@ jobs:
       # Add additional options to the MSBuild command line here (like platform or verbosity level).
       # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
       run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
+
+    - name: Test with pluginval
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: |
+        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Windows.zip -OutFile pluginval.zip
+        Expand-Archive pluginval.zip -DestinationPath .
+        ./pluginval.exe --validate-in-process "./Builds/VisualStudio2022/x64/${{env.BUILD_CONFIGURATION}}/VST3/Arpligner.vst3"
+        if ( !$? ) { echo "Plugival test suite failed"; exit 1 }
